global:
  scrape_interval: 5s
  scrape_timeout: 5s
  evaluation_interval: 5s
#  scrape_interval: 15s
#  scrape_timeout: 10s
#  evaluation_interval: 15s
alerting:
  alertmanagers:
  - static_configs:
    - targets: []
    scheme: http
    timeout: 10s
    api_version: v1
scrape_configs:
- job_name: otel-demo-pricing
  honor_timestamps: true
  # scrape_interval: 15s
  # scrape_timeout: 15s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - host.docker.internal:5206 
    # - localhost:5206            
- job_name: otel-demo-pricing-ssl
  honor_timestamps: true
  # scrape_interval: 15s
  # scrape_timeout: 15s
  metrics_path: /metrics
  scheme: https
  static_configs:
  - targets:
    - host.docker.internal:7151 
    # - localhost:7151            
- job_name: otel-demo-shipping
  honor_timestamps: true
  # scrape_interval: 15s
  # scrape_timeout: 15s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - host.docker.internal:5041 
    # - localhost:5041            
- job_name: otel-demo-shipping-ssl
  honor_timestamps: true
  # scrape_interval: 15s
  # scrape_timeout: 15s
  metrics_path: /metrics
  scheme: https
  tls_config:
    insecure_skip_verify: true
  static_configs:
  - targets:
    - host.docker.internal:7152 
    # - localhost:7152            
- job_name: otel-demo-store
  honor_timestamps: true
  # scrape_interval: 15s
  # scrape_timeout: 15s
  metrics_path: /metrics
  scheme: http
  static_configs:
  - targets:
    - host.docker.internal:5032 
    # - localhost:5032            
- job_name: otel-demo-store-ssl
  honor_timestamps: true
  # scrape_interval: 15s
  # scrape_timeout: 15s
  metrics_path: /metrics
  scheme: https
  static_configs:
  - targets:
    - host.docker.internal:7049 
    # - localhost:7049            
 

# - job_name: the-job-name
#   honor_timestamps: true
#   scrape_interval: 15s
#   scrape_timeout: 10s
#   metrics_path: /metrics
#   scheme: http
#   static_configs:
#   - targets:
#     - localhost:9090
